# fly.toml app configuration file generated for store-management-processor on 2024-11-16T00:09:40+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'store-management-processor'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
